permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments
host: 0.0.0.0
port: 5000
plugins:
  - jekyll-paginate
paginate: 6
comments: true
paginate_path: "/page/:num"
source: source
destination: _site
scholar:
  style: apa
  locale: en
  source: ./_bibliography
  sort_by: year
  order: descending
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true

sass:
  sass_dir: _scss
  style: compressed
# Site settings
title: Blog
description: "Henry Ruiz Blog"
email: henryruiz22@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "http://haruiz.github.io"
repository: "https://github.com/haruiz"
disqus_shortname: "haruiz"
google_analytics: UA-52446115-1
highlight:
  #theme: googlecode
  theme: vs
  #theme: xcode
# social footer
social:
  github:
    slug: github
    link: https://github.com/haruiz
  facebook:
    slug: facebook
    link: https://www.facebook.com/devharuiz
  twitter:
    slug: twitter
    link: https://twitter.com/devharuiz
  instagram:
    slug: instagram
    link: https://www.instagram.com/henryruizdev/
  linkedin:
    slug: linkedin
    link: https://www.linkedin.com/in/haruiz/